docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  tags:
    - shell
    - opti
  services:
    - docker:dind
  before_script:
    - docker login -u "$ALIYUN_DOCKER_USERNAME" -p "$ALIYUN_DOCKER_PASSWORD" $ALIYUN_DOCKER_URL
  script:
    - docker build --pull -t "$ALIYUN_DOCKER_URL/$CI_PROJECT_PATH" .
    - docker push "$ALIYUN_DOCKER_URL/$CI_PROJECT_PATH"
  only:
    - master
